version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitTest1Project
  gitServerName: SanthoshKUserSanthosh
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.gittest1.integrations:e1
  packages:
  - name: GitTest1Project
    version: "1.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.1.0.0.1973
